before_script:
  - sudo apt-get update -qq && sudo apt-get install -y -qq libtool pkg-config python3-openssl gir1.2-gtk-3.0 python3-gi python3-nbxmpp-nightly python3-cairo python3-pip
  - sudo apt-get build-dep -y -qq gajim-default-nightly
  - sudo pip3 install pylint==2.1.1

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - python3 setup.py test -s test.no_gui

run-mypy:
  stage: test
  script:
    - mypy gajim

run-pylint:
  stage: test
  script:
    - pylint3 --version
    - pylint --version
    - scripts/dev/pylint-ci.sh --jobs=2 gajim

run-appdata:
  stage: test
  script:
    - appstream-util validate data/org.gajim.Gajim.appdata.xml.in

run-build:
  stage: build
  script:
    - python3 setup.py sdist
    - cd dist
    - export FN="gajim-default-"$(date +%F)".tar"
    - mv gajim-*.tar.gz $FN.gz
    - mkdir tmp_add_plugins
    - mv $FN.gz tmp_add_plugins/
    - cd tmp_add_plugins/
    - tar xzf $FN.gz
    - rm $FN.gz
    - export GF=$(find . -maxdepth 1 -type d -name 'gajim-*')
    - mkdir -p $GF/gajim/data/plugins/
    - cd $GF/gajim/data/plugins/
    - curl -O https://ftp.gajim.org/plugins_1/plugin_installer.zip
    - unzip plugin_installer.zip
    - rm plugin_installer.zip
    - cd ../../../..
    - tar czf ../$FN.gz gajim-*
    - cd ..
    - rm -rf tmp_add_plugins
    - scp $FN.gz panoramix:/var/www/gajim/downloads/snap/ci/gajim-default-$CI_COMMIT_SHA.tar.gz

  artifacts:
    name: "gajim-default-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - gajim-default-2???-??-??.tar.gz
