before_script:
  - sudo apt-get update -qq && sudo apt-get install -y -qq libtool pkg-config python3-openssl gir1.2-gtk-3.0 python3-gi python3-nbxmpp-nightly pylint3 python3-cairo
  - sudo apt-get build-dep -y -qq gajim-default-nightly

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - python3 setup.py test_nogui

run-mypy:
  stage: test
  script:
    - mypy gajim

run-pylint:
  stage: test
  script:
    - pylint3 --jobs=2 --disable=C0103,C0302,C0330,C0411,C0412,C0413,E0203,E0401,E0611,E0710,E0712,E1101,E1102,E1128,E1133,E1136,R0201,R0901,R0904,R0913,R0916,R1702,R1706,R1711,R1716,W0201,W0212,W0221,W0223,W0311,W0401,W0603,W0613,W0614 gajim

run-build:
  stage: build
  script:
    - python3 setup.py sdist
    - cd dist
    - export FN="gajim-default-"$(date +%F)".tar"
    - mv gajim-*.tar.gz $FN.gz
    - mkdir tmp_add_plugins
    - mv $FN.gz tmp_add_plugins/
    - cd tmp_add_plugins/
    - tar xzf $FN.gz
    - rm $FN.gz
    - export GF=$(find . -maxdepth 1 -type d -name 'gajim-*')
    - mkdir -p $GF/gajim/data/plugins/
    - cd $GF/gajim/data/plugins/
    - curl -O https://ftp.gajim.org/plugins_1/plugin_installer.zip
    - unzip plugin_installer.zip
    - rm plugin_installer.zip
    - cd ../../../..
    - tar czf ../$FN.gz gajim-*
    - cd ..
    - rm -rf tmp_add_plugins
    - scp $FN.gz panoramix:/var/www/gajim/downloads/snap/ci/gajim-default-$CI_COMMIT_SHA.tar.gz

  artifacts:
    name: "gajim-default-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - gajim-default-2???-??-??.tar.gz
