image: ci-gajim:master

include:
- project: 'gajim/ci'
  ref: master
  file: '.gajim-ci.yml'

pyright:
  stage: test
  script:
    - pip3 install -I git+https://dev.gajim.org/gajim/gi-stubs.git
    - npm install pyright
    - python3 -V
    - $(npm bin)/pyright --version
    - $(npm bin)/pyright
  interruptible: true
  allow_failure: false

variables:
  NBXMPP_BRANCH: master
  PLUGINS_BRANCH: master
