repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        exclude: ".githooks/"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    - id: codespell
      pass_filenames: false
      additional_dependencies:
        - tomli

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.292
    hooks:
    - id: pyright
      pass_filenames: false
      additional_dependencies:
        - nbxmpp @ git+https://dev.gajim.org/gajim/python-nbxmpp.git
        - PyGObject-stubs @ git+https://github.com/pygobject/pygobject-stubs.git
        - python-gitlab
        - ruamel.yaml
        - sentry-sdk
      stages: [manual]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
