repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.206
    hooks:
      - id: ruff

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.286
    hooks:
    - id: pyright
