[build-system]
requires = [
  "setuptools >= 43.0.0",
]
build-backend = "setuptools.build_meta"


[tool.codespell]
skip = "*__pycache__*,gajim/gui,gajim/data/icons,gajim/data/sounds,gajim/data/emoticons"
ignore-words-list = "claus,pres,ser,trough"
